apiVersion: v1
kind: Pod                                            
metadata:
  name: vault
  labels:
    app: vault                         
spec:                                                
  containers:
    - image: hashicorp/vault:latest
      name: vault                             
      ports:
      - containerPort: 8200
        
---

apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault  
spec:
  selector:
    app: vault
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP