apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  REACT_APP_USERNAME: "yerrange"
  REACT_APP_COMPANY_NAME: "feel_good_inc"

---

apiVersion: apps/v1
kind: ReplicaSet                                            
metadata:
  name: frontend-replica
  labels:
    app: frontend                   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ifilyaninitmo/itdt-contained-frontend:master
          name: frontend-container
          ports:
            - containerPort: 3000
          envFrom:
          - configMapRef:
              name: frontend-env

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 8200
      targetPort: 3000
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  tls:
    - hosts:
        - yerrange.local
      secretName: frontend-tls
  rules:
  - host: yerrange.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8200